global_frame: map
rolling_window: false
track_unknown_space: true

update_frequency: 3.0
publish_frequency: 2.0
resolution: 0.025

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
