global_frame: odom
rolling_window: true
track_unknown_space: true

update_frequency: 3.0
publish_frequency: 2.0
resolution: 0.025

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
